### ISSUE TITLE
Possibly add some unit (integration) tests for message parsing 

### ISSUE THREAD

**Issue by creesch** [creesch/minecraft-web-chat#16]
Considering the repo is now setup for nodejs and the fact that the javascript files have been turned into modules makes it fairly easy to import `message_parsing.mjs` into `vitest` or some other unittest framework.  

Thinking about it, I am not entirely sure if it makes sense to have actual unit tests for the individual functions. That might be overkill, certainly after the fact. 

But to prevent regression in the future it might make sense to go for unit integration level tests where a variety of minecraft JSON messages are fed in to validate basic parsing.  @danthedaniel  thoughts?

**Comment by danthedaniel** [comment]
I always try to start with end-to-end tests. Is it possible to do that in CI for a fabric mod? It might require too much RAM and OpenGL acceleration to make that happen.

Otherwise it’s pretty easy to have a list of different component structures and to validate output. 

By the way, I’m currently working on changes to:

1. Thoroughly validate component structures up front and remove all of the validation down the line. 
2. Output HTML elements and not strings. 

So it may be best to hold off until that’s merged today.

**Comment by creesch** [comment]
Yeah no I am not going to add e2e testing to the mod itself. That is going to be a pain with very little gain.  I was simply looking at what is the most complex bit of code there currently is and that is the message parser.

**Comment by danthedaniel** [comment]
I'll happily add a few basic JS tests to get us started. I'll use `vitest`. Where do you want the tests to go? I see a couple reasonable options.

1. In the root at `src/test/`
2. Closer to the tested code in `src/client/test/`

**Comment by creesch** [comment]
With option 2 they might be packaged. 

`src/test/web/` seems like a good option to me. Or if we want to make it really clear `src/test/client/web`

**Comment by danthedaniel** [comment]
Does web mean JS? What would the server be called? They're both web related.

**Comment by creesch** [comment]
> Does web mean JS? What would the server be called? They're both web related.

Web is the directory in resources all the static files are in. Might as well clarify that then `src/test/client/resources/web`.

**Comment by danthedaniel** [comment]
Yeah I realized that and deleted my comment. But you got here too fast!
